services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file: .env
    depends_on:
      - backend

  backend:
    build:
      context: ./flask-backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    env_file: flask-backend/.env
